Clean up simapp
CudoVentures/cudos-node pull request #107
Opened 2023-12-25 08:18 UTC by dao-notional

Cleanup `simapp` folder and test cases related .

2023-12-25 10:28 UTC, nghuyenthevinh2000 commented
LGTM! simapp folder is not even used that much

2024-01-05 01:55 UTC, nbaum commented on x/cudoMint/abci_test.go
>  }
In my opinion, it is neater to just delete this code, since it is in the commit history if we find we need it again. What do you think?

2024-01-05 01:57 UTC, nbaum commented on x/cudoMint/abci_test.go
>  }
And given this is the only test in the file, just delete the file?

2024-01-05 02:00 UTC, nbaum requested changes
mint test aside, lgtm

2024-01-05 02:00 UTC, nbaum commented on x/cudoMint/abci_test.go
>  }
In my opinion, it is neater to just delete this code, since it is in the commit history if we find we need it again. And, given this is the only test in the file, we can just delete the file.

What do you think?

2024-01-05 02:49 UTC, dao-notional commented on x/cudoMint/abci_test.go
>  }
This test will be replaced with new `apptesting` helper in #109. So for now, we can delete it in this PR, and let #109 implement it later

2024-01-10 09:53 UTC, closed without merging