CUDOS-682 / Changing approvedAddresses structure
CudoVentures/cudos-node pull request #26
Opened 2022-03-02 15:27 UTC by SpaghettiOverload

2022-03-04 14:09 UTC, Infra1515 requested changes
Seems ok, please take note of my comments and lets discuss them
Also, regarding the changes for the .pb.go go files - can you try to generate them the same way it is done in the GravityBridge ? ( that is - not using starport generate proto-go )
@kstoykov can probably tell us more how exactly is he generating the proto files for the cudos-node project

2022-03-04 14:09 UTC, Infra1515 commented on x/nft/keeper/keeper_test.go
> +func (suite *IntegrationTestKeeperSuite) isApprovedAddress(nft *types.BaseNFT, sender *sdk.AccAddress) bool {
Why do you define this here ? It is defined in the keeper and can be reused again from there like so:
suite.keeper.IsApprovedAddress . 
Also it would be better if it is a public method in the keeper ( starts with capital letter ).

2022-03-04 14:09 UTC, Infra1515 commented on x/nft/keeper/nft.go
> +			nft.ApprovedAddresses = append(nft.ApprovedAddresses[:i], nft.ApprovedAddresses[i+1:]...)
Add a comment how this exactly is functioning (  shift all of the elements at the right of the deleting index by one to the left ) or best extract it to self-explanatory function
```
func remove(slice []int, s int) []int {
    return append(slice[:s], slice[s+1:]...)
}
```

2022-03-04 14:09 UTC, Infra1515 commented on x/nft/keeper/nft_test.go
> +	assert.Equal(suite.T(), true, suite.isApprovedAddress(&nft, &address3))
same as above, use the keeper

2022-03-04 14:09 UTC, Infra1515 commented on x/nft/keeper/nft_test.go
> +	assert.Equal(suite.T(), suite.isApprovedAddress(&nft, &address2), true)
keeper here

2022-03-05 09:53 UTC, SpaghettiOverload commented
@Infra1515 Further commenting on .proto files parsing. I was able to parse files without Starport, using the protobuf cli - protoc. It seems the output depends and may vary on the plugins involved, I've also tested the command from the GravityBridge as belows:

`protoc \             
  -I=. \
  -I="third_party/proto" \
  --gocosmos_out=plugins=interfacetype+grpc,\
Mgoogle/protobuf/any.proto=github.com/cosmos/cosmos-sdk/codec/types:. \
  $(find "./cudos/cudoMint" -maxdepth 1 -name 'mint.proto')`

The generated mint.pb.go file is literally the same, as the one generated with the Starport commands, meaning that the difference with the mint.pb.go from cudos-dev probably comes from the local version of the protobuffer installed that is used in the process rather than import changes. Running protoc --version on my local machine returns - libprotoc 3.16.0, if known which were the version used on -dev, it can be tested further. Also, there is not much of a useful information for the serialized byte arrays [https://stackoverflow.com/questions/61960313/whats-the-byte-array-in-my-generated-protocol-buffer-code-for](url)

2022-03-07 16:35 UTC, merged